const http = require('http');
const tables = [
  'CD_ASSEMBLY','CD_ASSEMBLY_COMP','CD_CEMENT_JOB','CD_FLUID','CD_HOLE_SECT_GROUP',
  'CD_LESSON','CD_PERFORATE','CD_PRESSURE_SURVEY','CD_TEST','CD_WELLHEAD',
  'CD_WELLHEAD_COMP','CD_WELLHEAD_COMP_OUTLET','CD_WELLHEAD_COMPLETION_LINK',
  'CD_WELLHEAD_HANGER','CD_WELLHEAD_HANGER_CONTROL','CD_WELLHEAD_TEST',
  'CD_WEQP_CONV_PUMP','CD_WEQP_GRAVEL_PACK_SCREEN',
  'DM_ACTIVITY','DM_AFE_EVENT_LINK','DM_ANCHOR_OP','DM_BHA_OP','DM_BIT_OP',
  'DM_BOILER_OP','DM_BULK','DM_BULK_TRAN','DM_CARBIDE_LAG','DM_CASING',
  'DM_CENTRIFUGE_OP','DM_CHROMATOGRAPHY','DM_COMPANY','DM_COMPANY_DAILY',
  'DM_CONV_PUMP','DM_CORE','DM_COUNTER_WEIGHT','DM_CREW_OP','DM_CUTTINGS',
  'DM_DAILY','DM_DAILYCOST','DM_DAILY_COMPLETION','DM_DAILY_CT_OP',
  'DM_DAILY_DITCH_MAGNET','DM_DAILY_EQUIPMENT','DM_DAILY_FLARING',
  'DM_DAILY_GLV_TEST','DM_DAILY_NOTIFICATION','DM_DAILY_SSSV_TEST',
  'DM_DAILY_UBD','DM_DEGASSER_OP','DM_DISCHARGE','DM_DISPOSAL','DM_DRILLINE_OP',
  'DM_DST','DM_ENVIRONMENTAL','DM_ESP','DM_FISHING','DM_FISHING_FREE_POINT',
  'DM_FISHING_RESPONSIBLE','DM_FISHING_RESULTS','DM_FISHING_STRING_SHOT',
  'DM_FLUID_BALANCE','DM_FLUID_HAUL','DM_FLUID_HAUL_DETAIL','DM_FLUID_INPUT',
  'DM_FLUID_LOSS','DM_FLUID_LOSS_HOLE_SECT','DM_GAS_LIFT','DM_GAS_PEAK',
  'DM_GENERAL_WORK','DM_GEOLOGY_DAILY','DM_GRAVEL_PACK','DM_GUIDELINE_OP',
  'DM_HOTNOTE','DM_HSE','DM_HYDROCLONE_OP','DM_INCIDENT','DM_INCIDENT_COST',
  'DM_INCIDENT_DETAIL','DM_INTERMEDIATE_CIRC','DM_KICK','DM_LOG',
  'DM_MATERIAL_TRANSFER','DM_MOTOR_OP','DM_MUDGAS','DM_MUD_PRODUCT',
  'DM_MUD_PRODUCT_TRAN','DM_MUD_VOLUME','DM_OPER_EQUIP_FAIL',
  'DM_OPER_EQUIP_FAIL_STATUS','DM_PCP','DM_PERSONNEL','DM_PERSONNEL_DAILY',
  'DM_PIPE_DATA','DM_PIPE_RUN','DM_PIPE_TALLY','DM_PIT_OP','DM_PRODUCED',
  'DM_PLUNGER_ACC','DM_PLUNGER_LIFT','DM_PLUNGER_LIFT_STAGE_SYSTEM',
  'DM_PRIME_MOVER','DM_PROD_EQUIP_FAIL','DM_PUMP_JACK','DM_PUMP_OP',
  'DM_RECOVERY','DM_REPORT_JOURNAL','DM_RIG_ACTIVITY','DM_RIG_DECKLOG',
  'DM_RIG_DECKLOG_REMARKS','DM_RIG_OPERATION_EVENT_LINK','DM_RISERLINE_OP',
  'DM_RISER_OP','DM_SAFETY','DM_SAFETY_INCIDENT','DM_SAFETY_KICK_DETECT',
  'DM_SHAKERSCREEN_OP','DM_SHAKER_OP','DM_SPILLS','DM_SUCKLINE',
  'DM_SUCKLINE_DAILY','DM_SUCKLINE_PURPOSE','DM_SUCKLINE_SOLID',
  'DM_STIM_FET_TEST','DM_STIM_FLOWBACK','DM_STIM_FLOWPATH',
  'DM_STIM_FLOWPATH_STAGE','DM_STIM_FLUID','DM_STIM_FLUID_ADD',
  'DM_STIM_FLUID_SCHEDULE','DM_STIM_JOB','DM_STIM_PUMPING_DIAG',
  'DM_STIM_PUMP_FB_TEST','DM_STIM_RES_INTERVAL','DM_STIM_STAGE',
  'DM_STIM_STAGE_SUPPLEMENT','DM_STIM_STEP_TEST','DM_STIM_TREATMENT',
  'DM_STIM_TREATMENT_AC_COMP','DM_STIM_TREATMENT_ADDITIVE',
  'DM_STIM_TREATMENT_FLUID','DM_STIM_TREATMENT_PROPPANT',
  'DM_SUPPORT_VESSEL_DAILY','DM_TRANSFER_DETAIL','DM_TRANSFER_SUMMARY',
  'DM_UNDERWATER_DETAIL','DM_UNDERWATER_EQUIPMENT','DM_UNDERWATER_MATERIAL',
  'DM_UNDERWATER_MATERIAL_TRAN','DM_UNDERWATER_PRES','DM_UNDERWATER_OP',
  'DM_VESSEL_BULK_TRAN','DM_WB_OBSTRUCTION_STATUS','DM_WEATHER_CHECK',
  'DM_WEATHER_CURRENT','DM_WELLBORE_ZONE_ACTIVITY','DM_WELL_PLAN',
  'DM_WELL_PLAN_OFFSET','DM_WORK_DETAIL'
];

const inList = tables.map(t => "'" + t + "'").join(',');
const q = `SELECT object_name FROM all_objects WHERE object_type IN ('TABLE','VIEW','SYNONYM') AND object_name IN (${inList})`;
const body = JSON.stringify({sql: q});
const req = http.request({hostname:'localhost',port:3000,path:'/api/query',method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}}, res => {
  let d=''; res.on('data',c=>d+=c); res.on('end',()=>{
    const parsed = JSON.parse(d);
    const rows = parsed.rows || parsed;
    const found = new Set(rows.map(r => r.OBJECT_NAME));
    const missing = tables.filter(t => !found.has(t));
    console.log('Found:', found.size, '/', tables.length);
    console.log('Missing tables:');
    missing.forEach(t => console.log('  ' + t));
  });
});
req.write(body); req.end();
