// ─── Drop Backup Tables ──────────────────────────────────────────────────────
// Generates DROP TABLE statements to remove the backup tables after
// the move has been verified. Final cleanup step.

import { backupTableName } from './backup-suffix';

export interface DropBackupQuery {
  tableName: string;
  sql: string;
}

export function dropBackupQueries(suffix?: string): DropBackupQuery[] {
  const sfx = suffix || 'BK';
  const drop = (table: string): DropBackupQuery => ({
    tableName: table,
    sql: `DROP TABLE ${backupTableName(table, sfx)}`,
  });

  return [
    drop('CD_ASSEMBLY_COMP'),
    drop('CD_FLUID'),
    drop('CD_WELLHEAD_COMP'),
    drop('CD_WELLHEAD_COMP_OUTLET'),
    drop('CD_WELLHEAD_COMPLETION_LINK'),
    drop('CD_WELLHEAD_HANGER'),
    drop('CD_WELLHEAD_HANGER_CONTROL'),
    drop('CD_WELLHEAD_TEST'),
    drop('CD_WEQP_CONV_PUMP'),
    drop('CD_WEQP_GRAVEL_PACK_SCREEN'),
    drop('DM_ACTIVITY'),
    drop('DM_AFE_EVENT_LINK'),
    drop('DM_ANCHOR_OP'),
    drop('DM_BHA_OP'),
    drop('DM_BIT_OP'),
    drop('DM_BOILER_OP'),
    drop('DM_BULK'),
    drop('DM_BULK_TRAN'),
    drop('DM_CARBIDE_LAG'),
    drop('DM_CENTRIFUGE_OP'),
    drop('DM_CHROMATOGRAPHY'),
    drop('DM_COMPANY'),
    drop('DM_COMPANY_DAILY'),
    drop('DM_COUNTER_WEIGHT'),
    drop('DM_CREW_OP'),
    drop('DM_CUTTINGS'),
    drop('DM_DAILYCOST'),
    drop('DM_DAILY_COMPLETION'),
    drop('DM_DAILY_CT_OP'),
    drop('DM_DAILY_DITCH_MAGNET'),
    drop('DM_DAILY_EQUIPMENT'),
    drop('DM_DAILY_FLARING'),
    drop('DM_DAILY_GLV_TEST'),
    drop('DM_DAILY_NOTIFICATION'),
    drop('DM_DAILY_SSSV_TEST'),
    drop('DM_DAILY_UBD'),
    drop('DM_DEGASSER_OP'),
    drop('DM_DISCHARGE'),
    drop('DM_DISPOSAL'),
    drop('DM_DRILLINE_OP'),
    drop('DM_ENVIRONMENTAL'),
    drop('DM_FISHING_FREE_POINT'),
    drop('DM_FISHING_RESPONSIBLE'),
    drop('DM_FISHING_RESULTS'),
    drop('DM_FISHING_STRING_SHOT'),
    drop('DM_FLUID_BALANCE'),
    drop('DM_FLUID_HAUL_DETAIL'),
    drop('DM_FLUID_INPUT'),
    drop('DM_FLUID_LOSS'),
    drop('DM_FLUID_LOSS_HOLE_SECT'),
    drop('DM_GAS_LIFT'),
    drop('DM_GAS_PEAK'),
    drop('DM_GRAVEL_PACK'),
    drop('DM_GUIDELINE_OP'),
    drop('DM_HOTNOTE'),
    drop('DM_HSE'),
    drop('DM_HYDROCLONE_OP'),
    drop('DM_INCIDENT_COST'),
    drop('DM_INCIDENT_DETAIL'),
    drop('DM_INTERMEDIATE_CIRC'),
    drop('DM_MOTOR_OP'),
    drop('DM_MUDGAS'),
    drop('DM_MUD_PRODUCT'),
    drop('DM_MUD_PRODUCT_TRAN'),
    drop('DM_MUD_VOLUME'),
    drop('DM_OPER_EQUIP_FAIL_STATUS'),
    drop('DM_PERSONNEL'),
    drop('DM_PERSONNEL_DAILY'),
    drop('DM_PIPE_DATA'),
    drop('DM_PIPE_TALLY'),
    drop('DM_PIT_OP'),
    drop('DM_PLUNGER_ACC'),
    drop('DM_PLUNGER_LIFT_STAGE_SYSTEM'),
    drop('DM_PRIME_MOVER'),
    drop('DM_PRODUCED'),
    drop('DM_PROD_EQUIP_FAIL'),
    drop('DM_PUMP_JACK'),
    drop('DM_PUMP_OP'),
    drop('DM_RECOVERY'),
    drop('DM_RIG_ACTIVITY'),
    drop('DM_RIG_DECKLOG'),
    drop('DM_RIG_DECKLOG_REMARKS'),
    drop('DM_RIG_OPERATION_EVENT_LINK'),
    drop('DM_RISERLINE_OP'),
    drop('DM_RISER_OP'),
    drop('DM_SAFETY'),
    drop('DM_SAFETY_INCIDENT'),
    drop('DM_SAFETY_KICK_DETECT'),
    drop('DM_SHAKERSCREEN_OP'),
    drop('DM_SHAKER_OP'),
    drop('DM_SLICKLINE_DAILY'),
    drop('DM_SLICKLINE_PURPOSE'),
    drop('DM_SLICKLINE_SOLID'),
    drop('DM_SPILLS'),
    drop('DM_STIM_FET_TEST'),
    drop('DM_STIM_FLOWBACK'),
    drop('DM_STIM_FLOWPATH'),
    drop('DM_STIM_FLOWPATH_STAGE'),
    drop('DM_STIM_FLUID'),
    drop('DM_STIM_FLUID_ADD'),
    drop('DM_STIM_FLUID_SCHEDULE'),
    drop('DM_STIM_PUMPING_DIAG'),
    drop('DM_STIM_PUMP_FB_TEST'),
    drop('DM_STIM_RES_INTERVAL'),
    drop('DM_STIM_STAGE'),
    drop('DM_STIM_STAGE_SUPPLEMENT'),
    drop('DM_STIM_STEP_TEST'),
    drop('DM_STIM_TREATMENT'),
    drop('DM_STIM_TREATMENT_AC_COMP'),
    drop('DM_STIM_TREATMENT_ADDITIVE'),
    drop('DM_STIM_TREATMENT_FLUID'),
    drop('DM_STIM_TREATMENT_PROPPANT'),
    drop('DM_SUPPORT_VESSEL_DAILY'),
    drop('DM_TRANSFER_DETAIL'),
    drop('DM_TRANSFER_SUMMARY'),
    drop('DM_UNDERWATER_DETAIL'),
    drop('DM_UNDERWATER_EQUIPMENT'),
    drop('DM_UNDERWATER_MATERIAL'),
    drop('DM_UNDERWATER_MATERIAL_TRAN'),
    drop('DM_UNDERWATER_PERS'),
    drop('DM_VESSEL_BULK_TRAN'),
    drop('DM_WEATHER_CHECK'),
    drop('DM_WEATHER_CURRENT'),
    drop('DM_WELLBORE_ZONE_ACTIVITY'),
    drop('DM_WELL_PLAN_OFFSET'),
    drop('DM_WORK_DETAIL'),
  ];
}
