// ─── Insert From Backup Queries ──────────────────────────────────────────────
// Generates INSERT INTO ... SELECT * FROM ..._BK statements to load child
// records from the backup tables (already updated with the target event_id)
// into the real tables. Used after move-parent-queries and delete-queries.

import { backupTableName } from './backup-suffix';

export interface InsertFromBackupQuery {
  tableName: string;
  sql: string;
}

export function insertFromBackupQueries(suffix?: string): InsertFromBackupQuery[] {
  const sfx = suffix || 'BK';
  const ins = (table: string): InsertFromBackupQuery => ({
    tableName: table,
    sql: `INSERT INTO ${table} SELECT * FROM ${backupTableName(table, sfx)}`,
  });

  return [
    ins('CD_ASSEMBLY_COMP'),
    ins('CD_FLUID'),
    ins('CD_WELLHEAD_COMP'),
    ins('CD_WELLHEAD_COMP_OUTLET'),
    ins('CD_WELLHEAD_COMPLETION_LINK'),
    ins('CD_WELLHEAD_HANGER'),
    ins('CD_WELLHEAD_HANGER_CONTROL'),
    ins('CD_WELLHEAD_TEST'),
    ins('CD_WEQP_GRAVEL_PACK_SCREEN'),
    ins('DM_ACTIVITY'),
    ins('DM_AFE_EVENT_LINK'),
    ins('DM_ANCHOR_OP'),
    ins('DM_BHA_OP'),
    ins('DM_BIT_OP'),
    ins('DM_BOILER_OP'),
    ins('DM_BULK'),
    ins('DM_BULK_TRAN'),
    ins('DM_CARBIDE_LAG'),
    ins('DM_CENTRIFUGE_OP'),
    ins('DM_CHROMATOGRAPHY'),
    ins('DM_COMPANY'),
    ins('DM_COMPANY_DAILY'),
    ins('DM_COUNTER_WEIGHT'),
    ins('DM_CREW_OP'),
    ins('DM_CUTTINGS'),
    ins('DM_DAILYCOST'),
    ins('DM_DAILY_COMPLETION'),
    ins('DM_DAILY_CT_OP'),
    ins('DM_DAILY_DITCH_MAGNET'),
    ins('DM_DAILY_EQUIPMENT'),
    ins('DM_DAILY_FLARING'),
    ins('DM_DAILY_GLV_TEST'),
    ins('DM_DAILY_NOTIFICATION'),
    ins('DM_DAILY_SSSV_TEST'),
    ins('DM_DAILY_UBD'),
    ins('DM_DEGASSER_OP'),
    ins('DM_DISCHARGE'),
    ins('DM_DISPOSAL'),
    ins('DM_DRILLINE_OP'),
    ins('DM_ENVIRONMENTAL'),
    ins('DM_FISHING_FREE_POINT'),
    ins('DM_FISHING_RESPONSIBLE'),
    ins('DM_FISHING_RESULTS'),
    ins('DM_FISHING_STRING_SHOT'),
    ins('DM_FLUID_BALANCE'),
    ins('DM_FLUID_HAUL_DETAIL'),
    ins('DM_FLUID_INPUT'),
    ins('DM_FLUID_LOSS'),
    ins('DM_FLUID_LOSS_HOLE_SECT'),
    ins('DM_GAS_LIFT'),
    ins('DM_GAS_PEAK'),
    ins('DM_GRAVEL_PACK'),
    ins('DM_GUIDELINE_OP'),
    ins('DM_HOTNOTE'),
    ins('DM_HSE'),
    ins('DM_HYDROCLONE_OP'),
    ins('DM_INCIDENT_COST'),
    ins('DM_INCIDENT_DETAIL'),
    ins('DM_INTERMEDIATE_CIRC'),
    ins('DM_MOTOR_OP'),
    ins('DM_MUDGAS'),
    ins('DM_MUD_PRODUCT'),
    ins('DM_MUD_PRODUCT_TRAN'),
    ins('DM_MUD_VOLUME'),
    ins('DM_OPER_EQUIP_FAIL_STATUS'),
    ins('DM_PERSONNEL'),
    ins('DM_PERSONNEL_DAILY'),
    ins('DM_PIPE_DATA'),
    ins('DM_PIPE_TALLY'),
    ins('DM_PIT_OP'),
    ins('DM_PLUNGER_ACC'),
    ins('DM_PLUNGER_LIFT_STAGE_SYSTEM'),
    ins('DM_PRIME_MOVER'),
    ins('DM_PRODUCED'),
    ins('DM_PROD_EQUIP_FAIL'),
    ins('DM_PUMP_JACK'),
    ins('DM_PUMP_OP'),
    ins('DM_RECOVERY'),
    ins('DM_RIG_ACTIVITY'),
    ins('DM_RIG_DECKLOG'),
    ins('DM_RIG_DECKLOG_REMARKS'),
    ins('DM_RIG_OPERATION_EVENT_LINK'),
    ins('DM_RISERLINE_OP'),
    ins('DM_RISER_OP'),
    ins('DM_SAFETY'),
    ins('DM_SAFETY_INCIDENT'),
    ins('DM_SAFETY_KICK_DETECT'),
    ins('DM_SHAKERSCREEN_OP'),
    ins('DM_SHAKER_OP'),
    ins('DM_SLICKLINE_DAILY'),
    ins('DM_SLICKLINE_PURPOSE'),
    ins('DM_SLICKLINE_SOLID'),
    ins('DM_SPILLS'),
    ins('DM_STIM_FET_TEST'),
    ins('DM_STIM_FLOWBACK'),
    ins('DM_STIM_FLOWPATH'),
    ins('DM_STIM_FLOWPATH_STAGE'),
    ins('DM_STIM_FLUID'),
    ins('DM_STIM_FLUID_ADD'),
    ins('DM_STIM_FLUID_SCHEDULE'),
    ins('DM_STIM_PUMPING_DIAG'),
    ins('DM_STIM_PUMP_FB_TEST'),
    ins('DM_STIM_RES_INTERVAL'),
    ins('DM_STIM_STAGE'),
    ins('DM_STIM_STAGE_SUPPLEMENT'),
    ins('DM_STIM_STEP_TEST'),
    ins('DM_STIM_TREATMENT'),
    ins('DM_STIM_TREATMENT_AC_COMP'),
    ins('DM_STIM_TREATMENT_ADDITIVE'),
    ins('DM_STIM_TREATMENT_FLUID'),
    ins('DM_STIM_TREATMENT_PROPPANT'),
    ins('DM_SUPPORT_VESSEL_DAILY'),
    ins('DM_TRANSFER_DETAIL'),
    ins('DM_TRANSFER_SUMMARY'),
    ins('DM_UNDERWATER_DETAIL'),
    ins('DM_UNDERWATER_EQUIPMENT'),
    ins('DM_UNDERWATER_MATERIAL'),
    ins('DM_UNDERWATER_MATERIAL_TRAN'),
    ins('DM_UNDERWATER_PERS'),
    ins('DM_VESSEL_BULK_TRAN'),
    ins('DM_WEATHER_CHECK'),
    ins('DM_WEATHER_CURRENT'),
    ins('DM_WELLBORE_ZONE_ACTIVITY'),
    ins('DM_WELL_PLAN_OFFSET'),
    ins('DM_WORK_DETAIL'),
  ];
}
