// ─── Update Backup Event Queries ─────────────────────────────────────────────
// Generates UPDATE statements to set the event_id on the backup tables
// from the source event to the target event. Used after creating
// backup tables and before inserting records into the target event.

import { backupTableName } from './backup-suffix';

export interface UpdateBackupQuery {
  tableName: string;
  sql: string;
}

export function updateBackupQueries(
  wellId: string,
  srcEventId: string,
  tgtEventId: string,
  suffix?: string
): UpdateBackupQuery[] {
  const w = wellId;
  const src = srcEventId;
  const tgt = tgtEventId;
  const sfx = suffix || 'BK';

  const upd = (table: string): UpdateBackupQuery => ({
    tableName: table,
    sql: `UPDATE ${backupTableName(table, sfx)} SET event_id='${tgt}' WHERE well_id='${w}' AND event_id='${src}'`,
  });

  return [
    upd('CD_ASSEMBLY_COMP'),
    upd('CD_FLUID'),
    upd('CD_WELLHEAD_COMP'),
    upd('CD_WELLHEAD_COMP_OUTLET'),
    upd('CD_WELLHEAD_COMPLETION_LINK'),
    upd('CD_WELLHEAD_HANGER'),
    upd('CD_WELLHEAD_HANGER_CONTROL'),
    upd('CD_WELLHEAD_TEST'),
    upd('CD_WEQP_CONV_PUMP'),
    upd('CD_WEQP_GRAVEL_PACK_SCREEN'),
    upd('DM_ACTIVITY'),
    upd('DM_AFE_EVENT_LINK'),
    upd('DM_ANCHOR_OP'),
    upd('DM_BHA_OP'),
    upd('DM_BIT_OP'),
    upd('DM_BOILER_OP'),
    upd('DM_BULK'),
    upd('DM_BULK_TRAN'),
    upd('DM_CARBIDE_LAG'),
    upd('DM_CENTRIFUGE_OP'),
    upd('DM_CHROMATOGRAPHY'),
    upd('DM_COMPANY'),
    upd('DM_COMPANY_DAILY'),
    upd('DM_COUNTER_WEIGHT'),
    upd('DM_CREW_OP'),
    upd('DM_CUTTINGS'),
    upd('DM_DAILYCOST'),
    upd('DM_DAILY_COMPLETION'),
    upd('DM_DAILY_CT_OP'),
    upd('DM_DAILY_DITCH_MAGNET'),
    upd('DM_DAILY_FLARING'),
    upd('DM_DAILY_EQUIPMENT'),
    upd('DM_DAILY_GLV_TEST'),
    upd('DM_DAILY_NOTIFICATION'),
    upd('DM_DAILY_SSSV_TEST'),
    upd('DM_DAILY_UBD'),
    upd('DM_DEGASSER_OP'),
    upd('DM_DISCHARGE'),
    upd('DM_DISPOSAL'),
    upd('DM_DRILLINE_OP'),
    upd('DM_ENVIRONMENTAL'),
    upd('DM_FISHING_FREE_POINT'),
    upd('DM_FISHING_RESPONSIBLE'),
    upd('DM_FISHING_RESULTS'),
    upd('DM_FISHING_STRING_SHOT'),
    upd('DM_FLUID_BALANCE'),
    upd('DM_FLUID_HAUL_DETAIL'),
    upd('DM_FLUID_INPUT'),
    upd('DM_FLUID_LOSS'),
    upd('DM_FLUID_LOSS_HOLE_SECT'),
    upd('DM_GAS_LIFT'),
    upd('DM_GAS_PEAK'),
    upd('DM_GRAVEL_PACK'),
    upd('DM_GUIDELINE_OP'),
    upd('DM_HOTNOTE'),
    upd('DM_HSE'),
    upd('DM_HYDROCLONE_OP'),
    upd('DM_INCIDENT_COST'),
    upd('DM_INCIDENT_DETAIL'),
    upd('DM_INTERMEDIATE_CIRC'),
    upd('DM_MOTOR_OP'),
    upd('DM_MUDGAS'),
    upd('DM_MUD_PRODUCT'),
    upd('DM_MUD_PRODUCT_TRAN'),
    upd('DM_MUD_VOLUME'),
    upd('DM_OPER_EQUIP_FAIL_STATUS'),
    upd('DM_PERSONNEL'),
    upd('DM_PERSONNEL_DAILY'),
    upd('DM_PIPE_DATA'),
    upd('DM_PIPE_TALLY'),
    upd('DM_PIT_OP'),
    upd('DM_PLUNGER_ACC'),
    upd('DM_PLUNGER_LIFT_STAGE_SYSTEM'),
    upd('DM_PRIME_MOVER'),
    upd('DM_PRODUCED'),
    upd('DM_PROD_EQUIP_FAIL'),
    upd('DM_PUMP_JACK'),
    upd('DM_PUMP_OP'),
    upd('DM_RECOVERY'),
    upd('DM_RIG_ACTIVITY'),
    upd('DM_RIG_DECKLOG'),
    upd('DM_RIG_DECKLOG_REMARKS'),
    upd('DM_RIG_OPERATION_EVENT_LINK'),
    upd('DM_RISERLINE_OP'),
    upd('DM_RISER_OP'),
    upd('DM_SAFETY'),
    upd('DM_SAFETY_INCIDENT'),
    upd('DM_SAFETY_KICK_DETECT'),
    upd('DM_SHAKERSCREEN_OP'),
    upd('DM_SHAKER_OP'),
    upd('DM_SLICKLINE_DAILY'),
    upd('DM_SLICKLINE_PURPOSE'),
    upd('DM_SLICKLINE_SOLID'),
    upd('DM_SPILLS'),
    upd('DM_STIM_FET_TEST'),
    upd('DM_STIM_FLOWBACK'),
    upd('DM_STIM_FLOWPATH'),
    upd('DM_STIM_FLOWPATH_STAGE'),
    upd('DM_STIM_FLUID'),
    upd('DM_STIM_FLUID_ADD'),
    upd('DM_STIM_FLUID_SCHEDULE'),
    upd('DM_STIM_PUMPING_DIAG'),
    upd('DM_STIM_PUMP_FB_TEST'),
    upd('DM_STIM_RES_INTERVAL'),
    upd('DM_STIM_STAGE'),
    upd('DM_STIM_STAGE_SUPPLEMENT'),
    upd('DM_STIM_STEP_TEST'),
    upd('DM_STIM_TREATMENT'),
    upd('DM_STIM_TREATMENT_AC_COMP'),
    upd('DM_STIM_TREATMENT_ADDITIVE'),
    upd('DM_STIM_TREATMENT_FLUID'),
    upd('DM_STIM_TREATMENT_PROPPANT'),
    upd('DM_SUPPORT_VESSEL_DAILY'),
    upd('DM_TRANSFER_DETAIL'),
    upd('DM_TRANSFER_SUMMARY'),
    upd('DM_UNDERWATER_DETAIL'),
    upd('DM_UNDERWATER_EQUIPMENT'),
    upd('DM_UNDERWATER_MATERIAL'),
    upd('DM_UNDERWATER_MATERIAL_TRAN'),
    upd('DM_UNDERWATER_PERS'),
    upd('DM_VESSEL_BULK_TRAN'),
    upd('DM_WEATHER_CHECK'),
    upd('DM_WEATHER_CURRENT'),
    upd('DM_WELLBORE_ZONE_ACTIVITY'),
    upd('DM_WELL_PLAN_OFFSET'),
    upd('DM_WORK_DETAIL'),
  ];
}
